---
- name: setup_app_environment.yml
  hosts: all
  become: yes
  tasks:
    - name: Create directory app_data
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ rep }}"
    - name: Create a group app_group
      ansible.builtin.group:
        name: app_group
        state: present
    - name: Create a user app_user with a home directory
      ansible.builtin.user:
        name: app_user
        state: present
        home: "/home/app_user"
        shell: /bin/bash
        group: app_group
    - name: Change directory
      ansible.builtin.file:
        path: "{{ item }}"
        mode: '0744'
        owner: app_user
        group: app_group
      loop: "{{ rep }}"
